name: scan

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: '18 10 * * 3'

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for codeQL to write security events

jobs:
  fossa:
    name: fossa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@3d2ef181b1820d6dcd1972f86a767d18167fa19b # v3.0.1
        with:
          # FOSSA Push-Only API Token
          fossa-api-key: 956b9b92c5b16eeca1467cebe104f2c3
          github-token: ${{ github.token }}

  codeql:
    name: codeql
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@63470275e73bbef3ffab4f0bfff5b52e0772baf5 #codeql-bundle-20221020
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@63470275e73bbef3ffab4f0bfff5b52e0772baf5 #codeql-bundle-20221020
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@63470275e73bbef3ffab4f0bfff5b52e0772baf5 #codeql-bundle-20221020
